AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template provisions a standalone EC2 instance.

#Adding EC2 instance parameters for flexibility
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: CF-Keypair
      ImageId: ami-0c55b159cbfafe1f0
      AvailabilityZone: us-east-1

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
